<a href="https://colab.research.google.com/github/vikishan13/Surface-Crack-Detection-using-CNN/blob/main/Surface_Crack_Detection_using_Convolutional_neural_network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install opendatasets

In [2]:
import opendatasets as od
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
import tensorflow as tf

In [3]:
od.download("https://www.kaggle.com/datasets/arunrk7/surface-crack-detection")

Skipping, found downloaded files in "./surface-crack-detection" (use force=True to force download)


In [4]:
dataset_path = "/content/surface-crack-detection"

In [5]:
positive_path = "/content/surface-crack-detection/Positive"

In [6]:
import os # operating system
import cv2 # computer vision 2

In [7]:
images = [] # numerical information about each image will be stored
labels = [] # label of each image [whether positive(1) or negative(0)]
for file in os.listdir(positive_path):
  image_path = os.path.join(positive_path, file)
  print(image_path)
  img = cv2.imread(image_path)
  print(img)
  img = cv2.resize(img, (64, 64))
  img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB) # color scheme
  images.append(img)
  labels.append(1)

Streaming output truncated to the last 5000 lines.
/content/surface-crack-detection/Positive/09038.jpg
[[[163 182 190]
  [164 183 191]
  [167 186 194]
  ...
  [158 174 186]
  [158 174 186]
  [158 174 186]]

 [[160 179 187]
  [161 180 188]
  [164 183 191]
  ...
  [161 177 189]
  [160 176 188]
  [160 176 188]]

 [[158 175 184]
  [159 176 185]
  [161 178 187]
  ...
  [164 180 192]
  [163 179 191]
  [161 177 189]]

 ...

 [[161 178 187]
  [164 181 190]
  [167 184 193]
  ...
  [156 172 184]
  [156 172 184]
  [156 172 184]]

 [[161 178 187]
  [165 182 191]
  [168 185 194]
  ...
  [154 170 182]
  [155 171 183]
  [156 172 184]]

 [[163 180 189]
  [166 183 192]
  [169 186 195]
  ...
  [152 168 180]
  [154 170 182]
  [155 171 183]]]
/content/surface-crack-detection/Positive/00331.jpg
[[[123 135 137]
  [123 135 137]
  [124 136 138]
  ...
  [120 133 135]
  [121 134 136]
  [123 136 138]]

 [[124 136 138]
  [124 136 138]
  [125 137 139]
  ...
  [121 134 136]
  [122 135 137]
  [123 136 138]]

 [[124 

In [8]:
negative_path = "/content/surface-crack-detection/Negative"

In [9]:
for file in os.listdir(negative_path):
  image_path = os.path.join(negative_path, file)
  print(image_path)
  img = cv2.imread(image_path)
  print(img)
  img = cv2.resize(img, (64, 64))
  img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB) # color scheme
  images.append(img)
  labels.append(0)

Streaming output truncated to the last 5000 lines.
/content/surface-crack-detection/Negative/05974.jpg
[[[199 206 209]
  [197 204 207]
  [195 202 205]
  ...
  [178 191 199]
  [178 191 199]
  [178 191 199]]

 [[196 203 206]
  [195 202 205]
  [193 200 203]
  ...
  [177 190 198]
  [177 190 198]
  [177 190 198]]

 [[192 199 202]
  [192 199 202]
  [191 198 201]
  ...
  [176 189 197]
  [176 189 197]
  [176 189 197]]

 ...

 [[203 216 218]
  [200 213 215]
  [196 209 211]
  ...
  [189 200 208]
  [192 203 211]
  [195 206 214]]

 [[202 215 217]
  [199 212 214]
  [196 209 211]
  ...
  [189 200 208]
  [192 203 211]
  [195 206 214]]

 [[200 213 215]
  [199 212 214]
  [197 210 212]
  ...
  [189 200 208]
  [192 203 211]
  [195 206 214]]]
/content/surface-crack-detection/Negative/03578.jpg
[[[196 207 215]
  [203 214 222]
  [209 220 228]
  ...
  [165 176 180]
  [164 175 179]
  [162 173 177]]

 [[196 207 215]
  [204 215 223]
  [210 221 229]
  ...
  [165 176 180]
  [164 175 179]
  [162 173 177]]

 [[195 

In [10]:
images = np.array(images)
labels = np.array(labels)

In [11]:
images.shape

(40000, 64, 64, 3)

In [12]:
labels.shape

(40000,)

In [13]:
images[1]

array([[[195, 192, 187],
        [193, 190, 185],
        [189, 186, 181],
        ...,
        [194, 192, 184],
        [192, 188, 182],
        [200, 197, 190]],

       [[191, 188, 183],
        [190, 187, 182],
        [187, 184, 179],
        ...,
        [194, 191, 184],
        [196, 193, 186],
        [187, 184, 177]],

       [[196, 193, 188],
        [202, 199, 194],
        [194, 191, 186],
        ...,
        [185, 182, 175],
        [197, 194, 187],
        [192, 189, 182]],

       ...,

       [[139, 136, 132],
        [118, 115, 109],
        [119, 116, 109],
        ...,
        [201, 194, 184],
        [184, 177, 167],
        [170, 163, 153]],

       [[111, 107, 104],
        [ 88,  84,  81],
        [102,  99,  94],
        ...,
        [211, 203, 192],
        [199, 191, 180],
        [195, 187, 176]],

       [[ 59,  55,  54],
        [ 58,  54,  52],
        [ 62,  59,  54],
        ...,
        [224, 216, 203],
        [206, 198, 185],
        [217, 209, 196]]

In [14]:
X = images
y = labels
xtrain, xtest, ytrain, ytest = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [15]:
xtrain.shape

(32000, 64, 64, 3)

In [16]:
xtest.shape

(8000, 64, 64, 3)

In [17]:
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder()

In [18]:
# normalize xtrain and xtest
xtrain =xtrain / 255.0
xtest = xtest / 255.0

In [19]:
xtrain[1]

array([[[0.70588235, 0.69019608, 0.64313725],
        [0.72156863, 0.70196078, 0.65490196],
        [0.70980392, 0.69411765, 0.64705882],
        ...,
        [0.74117647, 0.7254902 , 0.67843137],
        [0.75294118, 0.7372549 , 0.69019608],
        [0.77254902, 0.7372549 , 0.70196078]],

       [[0.7372549 , 0.72156863, 0.6745098 ],
        [0.70196078, 0.68627451, 0.63921569],
        [0.70980392, 0.69411765, 0.64705882],
        ...,
        [0.77254902, 0.75686275, 0.70980392],
        [0.78431373, 0.76862745, 0.72156863],
        [0.78823529, 0.75294118, 0.71764706]],

       [[0.74117647, 0.7254902 , 0.67843137],
        [0.72156863, 0.70588235, 0.65882353],
        [0.70588235, 0.69411765, 0.64313725],
        ...,
        [0.77254902, 0.75686275, 0.70980392],
        [0.78431373, 0.76862745, 0.72156863],
        [0.78039216, 0.74509804, 0.70980392]],

       ...,

       [[0.70588235, 0.69019608, 0.64313725],
        [0.69803922, 0.68235294, 0.63529412],
        [0.72156863, 0

In [20]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, Dense

In [21]:
from tensorflow.keras.layers import Flatten, MaxPooling2D

In [22]:
model = Sequential()
model.add(Conv2D(32, (3,3), activation = 'relu', input_shape = (64, 64, 3)))
model.add(MaxPooling2D(2,2))
model.add(Conv2D(64, (3,3), activation = 'relu'))
model.add(MaxPooling2D(2,2))

In [23]:
model.add(Flatten())
model.add(Dense(64, activation = 'relu'))
model.add(Dense(1, activation = 'sigmoid'))

In [24]:
model.compile(optimizer = "adam", loss = "binary_crossentropy", metrics = ['accuracy'])

In [25]:
model.fit(xtrain, ytrain, epochs = 10, batch_size = 32, validation_data = (xtest, ytest))

Epoch 1/10
1000/1000 [==============================] - 12s 7ms/step - loss: 0.0993 - accuracy: 0.9667 - val_loss: 0.0540 - val_accuracy: 0.9812
Epoch 2/10
1000/1000 [==============================] - 5s 5ms/step - loss: 0.0476 - accuracy: 0.9864 - val_loss: 0.0378 - val_accuracy: 0.9884
Epoch 3/10
1000/1000 [==============================] - 6s 6ms/step - loss: 0.0448 - accuracy: 0.9877 - val_loss: 0.0374 - val_accuracy: 0.9896
Epoch 4/10
1000/1000 [==============================] - 5s 5ms/step - loss: 0.0366 - accuracy: 0.9898 - val_loss: 0.0498 - val_accuracy: 0.9887
Epoch 5/10
1000/1000 [==============================] - 6s 6ms/step - loss: 0.0273 - accuracy: 0.9920 - val_loss: 0.0249 - val_accuracy: 0.9921
Epoch 6/10
1000/1000 [==============================] - 6s 6ms/step - loss: 0.0254 - accuracy: 0.9923 - val_loss: 0.0296 - val_accuracy: 0.9925
Epoch 7/10
1000/1000 [==============================] - 6s 6ms/step - loss: 0.0179 - accuracy: 0.9942 - val_loss: 0.0237 - val_accuracy