<a href="https://colab.research.google.com/github/vikishan13/Surface-Crack-Detection-using-CNN/blob/main/Surface_Crack_Detection_using_Convolutional_neural_network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install opendatasets

In [2]:
import opendatasets as od
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
import tensorflow as tf

In [3]:
od.download("https://www.kaggle.com/datasets/arunrk7/surface-crack-detection")

Please provide your Kaggle credentials to download this dataset. Learn more: http://bit.ly/kaggle-creds
Your Kaggle username: vikishan13
Your Kaggle Key: ··········


100%|██████████| 233M/233M [00:12<00:00, 19.1MB/s]


In [4]:
dataset_path = "/content/surface-crack-detection"

In [5]:
positive_path = "/content/surface-crack-detection/Positive"

In [6]:
import os # operating system
import cv2 # computer vision 2

In [7]:
images = [] # numerical information about each image will be stored
labels = [] # label of each image [whether positive(1) or negative(0)]
for file in os.listdir(positive_path):
  image_path = os.path.join(positive_path, file)
  # print(image_path)
  img = cv2.imread(image_path)
  # print(img)
  img = cv2.resize(img, (64, 64))
  img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB) # color scheme
  images.append(img)
  labels.append(1)

In [8]:
negative_path = "/content/surface-crack-detection/Negative"

In [9]:
for file in os.listdir(negative_path):
  image_path = os.path.join(negative_path, file)
  # print(image_path)
  img = cv2.imread(image_path)
  # print(img)
  img = cv2.resize(img, (64, 64))
  img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB) # color scheme
  images.append(img)
  labels.append(0)

In [10]:
images = np.array(images)
labels = np.array(labels)

In [11]:
images.shape

(40000, 64, 64, 3)

In [12]:
labels.shape

(40000,)

In [13]:
images[1]

array([[[195, 192, 187],
        [193, 190, 185],
        [189, 186, 181],
        ...,
        [194, 192, 184],
        [192, 188, 182],
        [200, 197, 190]],

       [[191, 188, 183],
        [190, 187, 182],
        [187, 184, 179],
        ...,
        [194, 191, 184],
        [196, 193, 186],
        [187, 184, 177]],

       [[196, 193, 188],
        [202, 199, 194],
        [194, 191, 186],
        ...,
        [185, 182, 175],
        [197, 194, 187],
        [192, 189, 182]],

       ...,

       [[139, 136, 132],
        [118, 115, 109],
        [119, 116, 109],
        ...,
        [201, 194, 184],
        [184, 177, 167],
        [170, 163, 153]],

       [[111, 107, 104],
        [ 88,  84,  81],
        [102,  99,  94],
        ...,
        [211, 203, 192],
        [199, 191, 180],
        [195, 187, 176]],

       [[ 59,  55,  54],
        [ 58,  54,  52],
        [ 62,  59,  54],
        ...,
        [224, 216, 203],
        [206, 198, 185],
        [217, 209, 196]]

In [14]:
X = images
y = labels
xtrain, xtest, ytrain, ytest = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [15]:
xtrain.shape

(32000, 64, 64, 3)

In [16]:
xtest.shape

(8000, 64, 64, 3)

In [17]:
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder()

In [18]:
# normalize xtrain and xtest
xtrain =xtrain / 255.0
xtest = xtest / 255.0

In [19]:
xtrain[1]

array([[[0.70588235, 0.69019608, 0.64313725],
        [0.72156863, 0.70196078, 0.65490196],
        [0.70980392, 0.69411765, 0.64705882],
        ...,
        [0.74117647, 0.7254902 , 0.67843137],
        [0.75294118, 0.7372549 , 0.69019608],
        [0.77254902, 0.7372549 , 0.70196078]],

       [[0.7372549 , 0.72156863, 0.6745098 ],
        [0.70196078, 0.68627451, 0.63921569],
        [0.70980392, 0.69411765, 0.64705882],
        ...,
        [0.77254902, 0.75686275, 0.70980392],
        [0.78431373, 0.76862745, 0.72156863],
        [0.78823529, 0.75294118, 0.71764706]],

       [[0.74117647, 0.7254902 , 0.67843137],
        [0.72156863, 0.70588235, 0.65882353],
        [0.70588235, 0.69411765, 0.64313725],
        ...,
        [0.77254902, 0.75686275, 0.70980392],
        [0.78431373, 0.76862745, 0.72156863],
        [0.78039216, 0.74509804, 0.70980392]],

       ...,

       [[0.70588235, 0.69019608, 0.64313725],
        [0.69803922, 0.68235294, 0.63529412],
        [0.72156863, 0

In [20]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, Dense

In [21]:
from tensorflow.keras.layers import Flatten, MaxPooling2D

In [22]:
model = Sequential()
model.add(Conv2D(32, (3,3), activation = 'relu', input_shape = (64, 64, 3)))
model.add(MaxPooling2D(2,2))
model.add(Conv2D(64, (3,3), activation = 'relu'))
model.add(MaxPooling2D(2,2))

In [23]:
model.add(Flatten())
model.add(Dense(64, activation = 'relu'))
model.add(Dense(1, activation = 'sigmoid'))

In [24]:
model.compile(optimizer = "adam", loss = "binary_crossentropy", metrics = ['accuracy'])

In [25]:
model.fit(xtrain, ytrain, epochs = 10, batch_size = 32, validation_data = (xtest, ytest))

Epoch 1/10
1000/1000 [==============================] - 13s 7ms/step - loss: 0.0931 - accuracy: 0.9675 - val_loss: 0.0743 - val_accuracy: 0.9774
Epoch 2/10
1000/1000 [==============================] - 6s 6ms/step - loss: 0.0539 - accuracy: 0.9852 - val_loss: 0.0671 - val_accuracy: 0.9845
Epoch 3/10
1000/1000 [==============================] - 6s 6ms/step - loss: 0.0471 - accuracy: 0.9866 - val_loss: 0.0537 - val_accuracy: 0.9845
Epoch 4/10
1000/1000 [==============================] - 10s 10ms/step - loss: 0.0381 - accuracy: 0.9899 - val_loss: 0.0351 - val_accuracy: 0.9914
Epoch 5/10
1000/1000 [==============================] - 7s 7ms/step - loss: 0.0252 - accuracy: 0.9922 - val_loss: 0.0291 - val_accuracy: 0.9915
Epoch 6/10
1000/1000 [==============================] - 6s 6ms/step - loss: 0.0198 - accuracy: 0.9937 - val_loss: 0.0292 - val_accuracy: 0.9914
Epoch 7/10
1000/1000 [==============================] - 5s 5ms/step - loss: 0.0168 - accuracy: 0.9948 - val_loss: 0.0367 - val_accura

In [27]:
# Image taken from Google
import numpy as np
import cv2
image_path = "/content/crack-basement-wall-lg.jpg"
image = cv2.imread(image_path)
image = cv2.resize(image, (64, 64))
image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

In [28]:
image

array([[[188, 189, 184],
        [178, 182, 180],
        [171, 171, 166],
        ...,
        [202, 211, 214],
        [188, 187, 183],
        [205, 212, 215]],

       [[194, 188, 172],
        [162, 154, 142],
        [173, 169, 160],
        ...,
        [167, 170, 163],
        [219, 228, 226],
        [198, 204, 207]],

       [[172, 177, 173],
        [157, 167, 168],
        [159, 164, 157],
        ...,
        [187, 191, 192],
        [174, 179, 182],
        [217, 216, 214]],

       ...,

       [[186, 178, 165],
        [161, 153, 140],
        [176, 168, 155],
        ...,
        [164, 179, 186],
        [172, 187, 194],
        [180, 191, 193]],

       [[188, 178, 166],
        [194, 187, 169],
        [186, 183, 168],
        ...,
        [152, 165, 173],
        [153, 166, 174],
        [141, 154, 162]],

       [[196, 186, 176],
        [195, 187, 166],
        [182, 179, 162],
        ...,
        [157, 170, 178],
        [161, 174, 182],
        [153, 161, 164]]

In [29]:
image = np.expand_dims(image, axis = 0)
image.shape

(1, 64, 64, 3)

In [30]:
image = image / 255.0

In [32]:
pred_model = model.predict(image)
print(pred_model)
if pred_model > 0.5:
  print("Surface Crack Detected")
else:
  print("No Crack in the Surface")

1/1 [==============================] - 0s 17ms/step
[[0.99800724]]
Surface Crack Detected
